/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_DBG.h"
#include "UART_DBG_SPI_UART.h"
#include "UART_DBG_PINS.h"
#include "UART_DBG_SPI_UART_PVT.h"
#include "UART_DBG_PVT.h"
#include "UART_DBG_BOOT.h"
#include "UART_RX.h"
#include "UART_RX_aliases.h"
#include "UART_TX.h"
#include "UART_TX_aliases.h"
#include "UART_DBG_SCBCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

